# Information about a set of simulations
sim_set : 
  name : "Rescorla-Wagner learning rate (alpha) estimation: periodic design evaluation and optimization"
  authors : "Filip Melinscak"
  description : "A set of simulations which evaluate periodic designs for Rescorla-Wagner learning rate estimation and try to optimize them."
  date_created : "2018-08-09"
  results_path : "../results/rwae"
  
# Information about a specific simulation
sim_run : 
  name : "rwae_eval_design-ref_prior-ha"
  description : "Evaluation of the reference periodic design under a high learning rate in an RW model."
  date_created : "2018-08-09"
  rng_seed : 982018023 # Random number generator seed for the simulation
  n_exp : 256 # Number of simulated experiments
  n_sub : 1 # Number of simulated subjects per experiment
  verbose : false # Whether to print diagnostic messages
  parallel : true # Whether to fit models to experiments in parallel

# Information about the experimental design being evaluated     
exp_design :
  exp_design_func : "exp_onecue_rect" # Name of the Matlab function used to generate experiment stimuli from design variables
  desvars : # Design variables structure (input to exp_design_func)
    nTrials : 120 # Total number of trials to generate
    halfPeriod : 60 # Number of trials that comprise one half-period
    usProbFirst : 0.5 # Probability of the US in the first half-period
    usProbSecond : 0 # Probability of the US in the second half-period

# Information about the design criterion that is evaluated
design_criterion : 
  criterion_func : "loss_paramest_err" # Name of the Matlab function used to evaluate the criterion
  criterion_options :
    param_name : 'alphaInit' # Name of the target parameter.
    param_type : 'evo'
    error_type : 'abs' #  Type of estimation error. Expected values: ['sqr', 'abs']

# Information about the model space (here the same space is used for simulation and fitting)
model_space : 
  # RW(V) model (as a specific case of the LSSPD WA model)
  - name : 'RW(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : 0.3 # High learning rate
        eta : 0
        kappa : 1
      obs :
        intercept : 0
        slope : 1
        mixCoef : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init : []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : 0.001
        ub : 10
    params_fit_fixed : # Values of fixed parameters in the fitting model (these params do not count towards model complexity)
      evo : 
        eta : 0
        kappa : 1
      obs :
        mixCoef : 1
