# Information about a set of simulations
sim_set : 
  name : "Rescorla-Wagner learning rate (alpha) estimation: periodic design evaluation and optimization"
  authors : "Filip Melinscak"
  description : "A set of simulations which evaluate periodic designs for Rescorla-Wagner learning rate estimation and try to optimize them."
  date_created : "2018-08-09"
  results_path : "../results/rwae"
  
# Information about a specific simulation
sim_run : 
  name : "rwae_optim_vague-alpha"
  description : "Optimization of a periodic design under a vague learning rate prior in an RW model."
  date_created : "2018-08-09"
  rng_seed : 982018034 # Random number generator seed for the simulation

# Design evaluation options
eval_opts :
  n_exp : 32 # Number of simulated experiments per design evaluation and simulation model.
  verbose : false # Whether to print diagnostic messages
  parallel : true # Whether to fit models to experiments in parallel

# Optimization options (see 'bayesopt' Matlab function for details)
optim_opts :
  store_user_data_trace : false # Whether to save results of all simulations; default: false (Warning: can result in large result files if true)
  AcquisitionFunctionName : 'expected-improvement-plus'
  IsObjectiveDeterministic : false # Default: true
  ExplorationRatio : 0.5 # Propensity to explore (default: 0.5)
  MaxObjectiveEvaluations : 300 # Default: 30
  MaxTime : inf # In seconds, default: inf
  NumSeedPoints : 10 # Default: 4
  ConditionalVariableFcn :  # Conditional variable constraints
  NumCoupledConstraints : 0
  Verbose : 1 # [0 - no output, 1 - default, 2 - with diagnostic info]
  OutputFcn : 
  PlotFcn :

# Information about the experimental design being evaluated     
exp_design :
  exp_design_func : "exp_onecue_rect" # Name of the Matlab function used to generate experiment stimuli from design variables
  desvars_const : # Constant design variables structure
    n_sub : 1 # Number of simulated subjects per experiment
    nTrials : 120 # Total number of trials to generate
  desvars_optim : # Optimizable design variables (see 'optimizableVariable' class in Matlab)
    - name : 'halfPeriodFrac' # fraction of the total number of trials that comprise one half-period
      range : 
        - [0, 1]
      type : 'real'
    - name : 'usProbFirst' # Probability of the US in the first half-period
      range : 
        - [0, 1]
      type : 'real'
    - name : 'usProbSecond' # Probability of the US in the second half-period
      range : 
        - [0, 1]
      type : 'real'

# Information about the design criterion that is evaluated
design_criterion : 
  criterion_func : "loss_paramest_err" # Name of the Matlab function used to evaluate the criterion
  criterion_options :
    param_name : 'alphaInit' # Name of the target parameter.
    param_type : 'evo'
    error_type : 'abs' #  Type of estimation error. Expected values: ['sqr', 'abs']

# Information about the model space (here the same space is used for simulation and fitting)
model_space : 
  # RW(V) model (as a specific case of the LSSPD WA model)
  - name : 'RW(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : '@() unifrnd(0,1)' # Vague learning rate prior
        eta : 0
        kappa : 1
      obs :
        intercept : 0
        slope : 1
        mixCoef : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init : []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init : []
        lb : 0.001
        ub : 10
    params_fit_fixed : # Values of fixed parameters in the fitting model (these params do not count towards model complexity)
      evo : 
        eta : 0
        kappa : 1
      obs :
        mixCoef : 1
