# Information about a set of simulations
sim_set : 
  name : "LSSPD2011 design evaluation and optimization"
  authors : "Filip Melinscak"
  description : "A set of simulations which evaluate the reversal learning design of Li et al. (2011) (doi:10.1038/nn.2904) and try to optimize it."
  date_created : "2018-08-09"
  results_path : "../results/lsspd2011"
  
# Information about a specific simulation
sim_run : 
  name : "lsspd2011_eval_design-vagueopt_prior-point"
  description : "Evaluation of model selection accuracy of the two stage design optimized under a vague prior, with model space of Li et al. (2011) (doi:10.1038/nn.2904), under a point evaluative sampling prior."
  date_created : "2018-08-09"
  rng_seed : 982018013 # Random number generator seed for the simulation
  n_exp : 256 # Number of simulated experiments
  n_sub : 1 # Number of simulated subjects per experiment
  verbose : false # Whether to print diagnostic messages
  parallel : true # Whether to fit models to experiments in parallel

# Information about the experimental design being evaluated     
exp_design :
  exp_design_func : "exp_twostage_twocueonly" # Name of the Matlab function used to generate experiment stimuli from design variables
  desvars : # Design variables structure (input to exp_design_func)
    nTrialsAll : 
      - [60, 60] # Trials per each stage
    probA_1 : 0.5616
    probUS_A_1 : 0.65478
    probUS_B_1 : 0.021145
    probA_2 : 0.25017
    probUS_A_2 : 0.4298
    probUS_B_2 : 0.97958

# Information about the design criterion that is evaluated
design_criterion : 
  criterion_func : "loss_modsel_err" # Name of the Matlab function used to evaluate the criterion
  criterion_options :
    criterion : 'bic' # Name of the model selection criterion.
    do_logodds : true # Whether to transform the error rate from the probability to log-odds scale.

# Information about the model space (here the same space is used for simulation and fitting)
model_space : 
  # RW(V) model (as a specific case of the LSSPD WA model)
  - name : 'RW(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : 0.926
        eta : 0
        kappa : 1
      obs :
        intercept : 0
        slope : 1
        mixCoef : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10
    params_fit_fixed : # Values of fixed parameters in the fitting model (these params do not count towards model complexity)
      evo : 
        eta : 0
        kappa : 1
      obs :
        mixCoef : 1
  # Hybrid(V) model (as a specific case of the LSSPD WA model)
  - name : 'Hybrid(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : 0.926
        eta : 0.166
        kappa : 0.857
      obs :
        intercept : 0
        slope : 1
        mixCoef : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'eta'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'kappa'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10
    params_fit_fixed : # Values of fixed parameters in the fitting model (these params do not count towards model complexity)
      obs :
        mixCoef : 1
  # Hybrid(alpha) model (as a specific case of the LSSPD WA model)
  - name : 'Hybrid(alpha)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : 0.926
        eta : 0.166
        kappa : 0.857
      obs :
        intercept : 0
        slope : 1
        mixCoef : 0
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'eta'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'kappa'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10
    params_fit_fixed : # Values of fixed parameters in the fitting model (these params do not count towards model complexity)
      obs :
        mixCoef : 0
  # Hybrid(V+alpha) model (as a specific case of the LSSPD WA model)
  - name : 'Hybrid(V+alpha)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_lsspd_batch' # Name of the NSSM evolution function
    obs_func : 'obs_wa_mix_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0
        alphaInit : 0.926
        eta : 0.166
        kappa : 0.857
      obs :
        intercept : 0
        slope : 1
        mixCoef : 0.5
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'alphaInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'eta'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'kappa'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'mixCoef'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10
