# Information about a set of simulations
sim_set : 
  name : "Kru2008 design evaluation and optimization"
  authors : "Filip Melinscak"
  description : "A set of simulations which evaluate the backward blocking design of Kruschke (2008, doi: 10.3758/LB.36.3.210) and try to optimize it."
  date_created : "2018-08-09"
  results_path : "../results/kru2008"
  
# Information about a specific simulation
sim_run : 
  name : "kru2008_optim_prior-point"
  description : "Optimization of a two stage experiment with two cues and their compound, for accurately selecting between models of Kruschke (2008, doi: 10.3758/LB.36.3.210), under a point sampling prior."
  date_created : "2018-08-09"
  rng_seed : 982018007 # Random number generator seed for the simulation

# Design evaluation options
eval_opts :
  n_exp : 32 # Number of simulated experiments per design evaluation and simulation model.
  verbose : false # Whether to print diagnostic messages
  parallel : true # Whether to fit models to experiments in parallel

# Optimization options (see 'bayesopt' Matlab function for details)
optim_opts :
  store_user_data_trace : false # Whether to save results of all simulations; default: false (Warning: can result in large result files if true)
  AcquisitionFunctionName : 'expected-improvement-plus'
  IsObjectiveDeterministic : false # Default: true
  ExplorationRatio : 0.5 # Propensity to explore (default: 0.5)
  MaxObjectiveEvaluations : 300 # Default: 30
  MaxTime : inf # In seconds, default: inf
  NumSeedPoints : 10 # Default: 4
  ConditionalVariableFcn :  # Conditional variable constraints
  NumCoupledConstraints : 0
  Verbose : 1 # [0 - no output, 1 - default, 2 - with diagnostic info]
  OutputFcn : 
  PlotFcn : 
  XConstraintFcn : '@(X) (X.probA_1 + X.probB_1 <= 1.0) & (X.probA_2 + X.probB_2 <= 1.0)'

# Information about the experimental design being evaluated
exp_design :
  exp_design_func : "exp_twostage_twocuecmpnd" # Name of the Matlab function used to generate experiment stimuli from design variables
  desvars_const : # Constant design variables structure
    n_sub : 1 # Number of simulated subjects per experiment
    nTrialsAll : 
      - [61, 61] # Trials per each stage
  desvars_optim : # Optimizable design variables (see 'optimizableVariable' class in Matlab)
    - name : 'probA_1'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probB_1'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_A_1'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_B_1'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_AB_1'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probA_2'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probB_2'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_A_2'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_B_2'
      range : 
        - [0, 1]
      type : 'real'
    - name : 'probUS_AB_2'
      range : 
        - [0, 1]
      type : 'real'

# Information about the design criterion that is evaluated
design_criterion : 
  criterion_func : "loss_modsel_err" # Name of the Matlab function used to evaluate the criterion
  criterion_options :
    criterion : 'bic' # Name of the model selection criterion.
    do_logodds : true # Whether to transform the error rate from the probability to log-odds scale.

# Information about the model space (here the same space is used for simulation and fitting)
model_space : 
  # RW model with affine observation function which maps associative weights to the output
  - name : 'RW(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_rw_batch' # Name of the NSSM evolution function
    obs_func : 'obs_affine_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0 # Value taken from Kruschke (2008)
        alpha : 0.08 # Value taken from Kruschke (2008)
      obs :
        intercept : 0
        slope : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init : []
        lb : -10
        ub : 10
      - name : 'alpha'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : 0
        ub : 1
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10
  # Kalman RW model with affine observation function which maps associative weights to the output
  - name : 'Kalman RW(V)'
    type : 'nssm' # Model type can be ['nssm' | 'generic']
    evo_func : 'evo_krw_batch' # Name of the NSSM evolution function
    obs_func : 'obs_affine_batch' # Name of the NSSM observation function
    prior_sim : # Sampling prior (either constant values or functions that generate random replicates from the prior)
      evo : 
        wInit : 0 # Value taken from Kruschke (2008)
        logSigmaWInit : 0.0 # 1 when exponentiated; value taken from Kruschke (2008)
        logTauSq : -20 # Approx. 0 when exponentiated; value taken from Kruschke (2008)
        logSigmaRSq : 1.3863 # Approx. 4 when exponentiated; value taken from Kruschke (2008) 
      obs :
        intercept : 0
        slope : 1
        sd : 0.2
    prior_fit : # Fitting prior and optimization boundaries and initialization
      - name : 'wInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'logSigmaWInit'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -30
        ub : 30
      - name : 'logTauSq'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -30
        ub : 30
      - name : 'logSigmaRSq'
        type : 'evo'
        logpdf : '@(x) 0'
        init: []
        lb : -30
        ub : 30
      - name : 'intercept'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'slope'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : -10
        ub : 10
      - name : 'sd'
        type : 'obs'
        logpdf : '@(x) 0'
        init: []
        lb : 0.001
        ub : 10

